import { AHKProfile, KeyMapping, TriggerState, Macro, MacroStep } from '../types';

/**
 * Format a key name for use inside AHK Send functions.
 * Alphanumeric characters are sent raw, special keys are wrapped in braces.
 */
export function formatAHKKey(key: string): string {
  const specialKeys = [
    'CapsLock', 'Space', 'Tab', 'Enter', 'Escape', 'Esc', 'Backspace', 'Delete', 'Insert',
    'Home', 'End', 'PgUp', 'PgDn', 'Up', 'Down', 'Left', 'Right',
    'LShift', 'RShift', 'LCtrl', 'RCtrl', 'LAlt', 'RAlt', 'LWin', 'RWin', 'AppsKey',
    'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12',
    'Volume_Up', 'Volume_Down', 'Volume_Mute', 'Media_Next', 'Media_Prev', 'Media_Play_Pause', 'Media_Stop',
    'Browser_Back', 'Browser_Forward', 'Browser_Refresh', 'Browser_Home', 'PrintScreen', 'ScrollLock', 'Pause',
    'LButton', 'RButton', 'MButton', 'WheelUp', 'WheelDown'
  ];

  if (specialKeys.some(sk => sk.toLowerCase() === key.toLowerCase())) {
    return `{${key}}`;
  }
  return key;
}

/**
 * Generate Action string for a given trigger state (v2)
 */
function getActionCodeV2(state: TriggerState, keyName: string): string {
  if (!state.enabled || state.actionType === 'none') {
    return `Send("${formatAHKKey(keyName)}") ; Forward original key`;
  }

  if (state.actionType === 'key') {
    if (!state.targetKey) return `; No target key specified`;
    return `Send("${formatAHKKey(state.targetKey)}")`;
  }

  if (state.actionType === 'macro') {
    if (!state.targetMacroId) return `; No macro ID specified`;
    return `PlayMacro_${state.targetMacroId}()`;
  }

  return '; Unknown action';
}

/**
 * Generate Action string for a given trigger state (v1)
 */
function getActionCodeV1(state: TriggerState, keyName: string): string {
  if (!state.enabled || state.actionType === 'none') {
    return `Send, ${formatAHKKey(keyName)} ; Forward original key`;
  }

  if (state.actionType === 'key') {
    if (!state.targetKey) return `; No target key specified`;
    return `Send, ${formatAHKKey(state.targetKey)}`;
  }

  if (state.actionType === 'macro') {
    if (!state.targetMacroId) return `; No macro ID specified`;
    return `Gosub, PlayMacro_${state.targetMacroId}`;
  }

  return '; Unknown action';
}

/**
 * Compile a single macro step to AHK v2
 */
function compileMacroStepV2(step: MacroStep): string {
  switch (step.type) {
    case 'keydown':
      return `    Send("${formatAHKKey(step.key)} down")`;
    case 'keyup':
      return `    Send("${formatAHKKey(step.key)} up")`;
    case 'text':
      // Escape quotes in text
      const escapedText = step.text.replace(/"/g, '`"');
      return `    SendText("${escapedText}")`;
    case 'delay':
      return `    Sleep(${step.duration})`;
    case 'click':
      if (step.x !== undefined && step.y !== undefined) {
        return `    Click(${step.x}, ${step.y}, "${step.button}")`;
      }
      return `    Click("${step.button}")`;
    default:
      return '    ; unknown step';
  }
}

/**
 * Compile a single macro step to AHK v1
 */
function compileMacroStepV1(step: MacroStep): string {
  switch (step.type) {
    case 'keydown':
      return `    Send, {${step.key} down}`;
    case 'keyup':
      return `    Send, {${step.key} up}`;
    case 'text':
      const escapedText = step.text.replace(/%/g, '`%');
      return `    SendRaw, ${escapedText}`;
    case 'delay':
      return `    Sleep, ${step.duration}`;
    case 'click':
      if (step.x !== undefined && step.y !== undefined) {
        return `    Click, ${step.x}, ${step.y}, ${step.button}`;
      }
      return `    Click, ${step.button}`;
    default:
      return '    ; unknown step';
  }
}

/**
 * Generate standard AHK Script from Profile definition
 */
export function generateAHKScript(profile: AHKProfile): string {
  const isV2 = profile.settings.ahkVersion === 'v2';
  
  if (isV2) {
    return generateAHKScriptV2(profile);
  } else {
    return generateAHKScriptV1(profile);
  }
}

/**
 * Generate AHK v2 Code
 */
function generateAHKScriptV2(profile: AHKProfile): string {
  const doubleTimeout = (profile.settings.doublePressTimeout / 1000).toFixed(2);
  const tripleTimeout = (profile.settings.triplePressTimeout / 1000).toFixed(2);
  const holdDur = (profile.settings.holdDuration / 1000).toFixed(2);

  let code = `; =========================================================================
; AutoHotkey v2 Script
; Generated by AHK Mapper & Macro Studio
; Profile: ${profile.name || 'Default Profile'}
; Description: ${profile.description || 'Custom keyboard layout and hotkeys.'}
; Created on: ${new Date().toLocaleDateString()}
; =========================================================================

#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode("Input")
SetWorkingDir(A_ScriptDir)

; Global Settings & Timers
; Double Tap Timeout: ${profile.settings.doublePressTimeout}ms
; Triple Tap Timeout: ${profile.settings.triplePressTimeout}ms
; Press & Hold Duration: ${profile.settings.holdDuration}ms

`;

  // 1. Macros Definition
  if (profile.macros && profile.macros.length > 0) {
    code += `; -------------------------------------------------------------------------\n`;
    code += `; CUSTOM MACROS\n`;
    code += `; -------------------------------------------------------------------------\n\n`;
    
    profile.macros.forEach(macro => {
      code += `PlayMacro_${macro.id}() {\n`;
      code += `    ; Name: ${macro.name}\n`;
      if (macro.description) {
        code += `    ; Description: ${macro.description}\n`;
      }
      
      if (macro.steps.length === 0) {
        code += `    Return\n`;
      } else {
        macro.steps.forEach((step, idx) => {
          code += compileMacroStepV2(step) + '\n';
          if (macro.useStandardDelays !== false && idx < macro.steps.length - 1) {
            code += `    Sleep(50)\n`;
          }
        });
      }
      code += `}\n\n`;
    });
  }

  // 2. Mappings Definition
  code += `; -------------------------------------------------------------------------\n`;
  code += `; KEY REMAPPINGS & HOTKEYS\n`;
  code += `; -------------------------------------------------------------------------\n\n`;

  Object.values(profile.mappings).forEach((mapping) => {
    const key = mapping.keyName;
    const s = mapping.single;
    const d = mapping.double;
    const t = mapping.triple;
    const h = mapping.hold;

    const hasSingleActive = s.enabled && s.actionType !== 'none';
    const hasDoubleActive = d.enabled && d.actionType !== 'none';
    const hasTripleActive = t.enabled && t.actionType !== 'none';
    const hasHoldActive = h.enabled && h.actionType !== 'none';

    // If no triggers are active/custom, skip generating AHK code entirely
    if (!hasSingleActive && !hasDoubleActive && !hasTripleActive && !hasHoldActive) {
      return;
    }

    const hasDouble = d.enabled;
    const hasTriple = t.enabled;
    const hasHold = h.enabled;

    // Custom threshold formatting
    const kHold = h.customTiming ? (h.customTiming / 1000).toFixed(2) : holdDur;
    const kDouble = d.customTiming ? (d.customTiming / 1000).toFixed(2) : doubleTimeout;
    const kTriple = t.customTiming ? (t.customTiming / 1000).toFixed(2) : tripleTimeout;

    code += `; --- Hotkeys for [${key}] ---\n`;

    // Case 1: Simple remapping only (no hold, double or triple press)
    if (!hasDouble && !hasTriple && !hasHold) {
      code += `$*${key}:: {\n`;
      code += `    ${getActionCodeV2(s, key)}\n`;
      code += `}\n\n`;
      return;
    }

    // Case 2: Multi-trigger (Hold, Double, Triple)
    code += `$*${key}:: {\n`;
    
    if (hasHold) {
      code += `    ; Wait for physical release within ${parseFloat(kHold) * 1000}ms to distinguish Tap vs Hold\n`;
      code += `    if (KeyWait("${key}", "T${kHold}")) {\n`;
      
      // Tap section
      if (hasDouble || hasTriple) {
        const doubleWaitTime = hasTriple ? kTriple : kDouble;
        code += `        ; Key was released early (Tap). Check if pressed again within ${parseFloat(doubleWaitTime) * 1000}ms\n`;
        code += `        if (KeyWait("${key}", "D T${doubleWaitTime}")) {\n`;
        
        // Second press occurred!
        if (hasTriple) {
          code += `            ; Second press occurred. Wait for release and check for 3rd press\n`;
          code += `            if (KeyWait("${key}", "T${kHold}")) {\n`;
          code += `                if (KeyWait("${key}", "D T${kDouble}")) {\n`;
          code += `                    ; --- TRIPLE PRESS ---\n`;
          code += `                    ${getActionCodeV2(t, key)}\n`;
          code += `                } else {\n`;
          code += `                    ; --- DOUBLE PRESS ---\n`;
          code += `                    ${getActionCodeV2(d, key)}\n`;
          code += `                }\n`;
          code += `            } else {\n`;
          code += `                ; Second press was held down instead of tapped\n`;
          code += `                ${getActionCodeV2(d, key)}\n`;
          code += `            }\n`;
        } else {
          // Just double tap
          code += `            ; --- DOUBLE PRESS ---\n`;
          code += `            ${getActionCodeV2(d, key)}\n`;
        }
        
        code += `        } else {\n`;
        code += `            ; --- SINGLE PRESS ---\n`;
        code += `            ${getActionCodeV2(s, key)}\n`;
        code += `        }\n`;
      } else {
        // Just single tap and hold
        code += `        ; --- SINGLE PRESS ---\n`;
        code += `        ${getActionCodeV2(s, key)}\n`;
      }
      
      code += `    } else {\n`;
      code += `        ; --- PRESS AND HOLD ---\n`;
      code += `        ${getActionCodeV2(h, key)}\n`;
      code += `        KeyWait("${key}") ; Wait for key to be physically released\n`;
      code += `    }\n`;
    } else {
      // No hold mapping, but has double and/or triple press
      code += `    ; Wait for physical release to verify it is a Tap\n`;
      code += `    KeyWait("${key}", "T0.20")\n`;
      const doubleWaitTime = hasTriple ? kTriple : kDouble;
      code += `    ; Check for second tap within ${parseFloat(doubleWaitTime) * 1000}ms\n`;
      code += `    if (KeyWait("${key}", "D T${doubleWaitTime}")) {\n`;
      
      if (hasTriple) {
        code += `        KeyWait("${key}", "T0.20")\n`;
        code += `        ; Check for third tap\n`;
        code += `        if (KeyWait("${key}", "D T${kDouble}")) {\n`;
        code += `            ; --- TRIPLE PRESS ---\n`;
        code += `            ${getActionCodeV2(t, key)}\n`;
        code += `        } else {\n`;
        code += `            ; --- DOUBLE PRESS ---\n`;
        code += `            ${getActionCodeV2(d, key)}\n`;
        code += `        }\n`;
      } else {
        code += `        ; --- DOUBLE PRESS ---\n`;
        code += `        ${getActionCodeV2(d, key)}\n`;
      }
      
      code += `    } else {\n`;
      code += `        ; --- SINGLE PRESS ---\n`;
      code += `        ${getActionCodeV2(s, key)}\n`;
      code += `    }\n`;
    }

    code += `}\n\n`;
  });

  return code;
}

/**
 * Generate AHK v1 Code
 */
function generateAHKScriptV1(profile: AHKProfile): string {
  const doubleTimeout = profile.settings.doublePressTimeout;
  const tripleTimeout = profile.settings.triplePressTimeout;
  const holdDur = profile.settings.holdDuration;

  let code = `; =========================================================================
; AutoHotkey v1.1 Script (Legacy compatibility)
; Generated by AHK Mapper & Macro Studio
; Profile: ${profile.name || 'Default Profile'}
; Description: ${profile.description || 'Custom keyboard layout and hotkeys.'}
; Created on: ${new Date().toLocaleDateString()}
; =========================================================================

#NoEnv
#SingleInstance, Force
SendMode, Input
SetWorkingDir, %A_ScriptDir%

; Global Settings & Timers
; Double Tap Timeout: ${doubleTimeout}ms
; Triple Tap Timeout: ${tripleTimeout}ms
; Press & Hold Duration: ${holdDur}ms

`;

  // 1. Mappings Definition
  code += `; -------------------------------------------------------------------------\n`;
  code += `; KEY REMAPPINGS & HOTKEYS\n`;
  code += `; -------------------------------------------------------------------------\n\n`;

  Object.values(profile.mappings).forEach((mapping) => {
    const key = mapping.keyName;
    const s = mapping.single;
    const d = mapping.double;
    const t = mapping.triple;
    const h = mapping.hold;

    const hasSingleActive = s.enabled && s.actionType !== 'none';
    const hasDoubleActive = d.enabled && d.actionType !== 'none';
    const hasTripleActive = t.enabled && t.actionType !== 'none';
    const hasHoldActive = h.enabled && h.actionType !== 'none';

    // If no triggers are active/custom, skip generating AHK code entirely
    if (!hasSingleActive && !hasDoubleActive && !hasTripleActive && !hasHoldActive) {
      return;
    }

    const hasDouble = d.enabled;
    const hasTriple = t.enabled;
    const hasHold = h.enabled;

    // Custom threshold formatting
    const kHoldSec = ((h.customTiming || holdDur) / 1000).toFixed(2);
    const kDoubleSec = ((d.customTiming || doubleTimeout) / 1000).toFixed(2);
    const kTripleSec = ((t.customTiming || tripleTimeout) / 1000).toFixed(2);

    code += `; --- Hotkeys for [${key}] ---\n`;

    // Case 1: Simple remapping only
    if (!hasDouble && !hasTriple && !hasHold) {
      code += `$*${key}::\n`;
      code += `    ${getActionCodeV1(s, key)}\n`;
      code += `return\n\n`;
      return;
    }

    // Case 2: Multi-trigger (Hold, Double, Triple) using ErrorLevel
    code += `$*${key}::\n`;
    
    if (hasHold) {
      code += `    ; Wait for physical release within ${kHoldSec}s (Hold threshold)\n`;
      code += `    KeyWait, ${key}, T${kHoldSec}\n`;
      code += `    if (ErrorLevel = 0) {\n`; // Key released early (Tap)
      
      if (hasDouble || hasTriple) {
        const doubleWaitTime = hasTriple ? kTripleSec : kDoubleSec;
        code += `        ; Wait for second press down\n`;
        code += `        KeyWait, ${key}, D T${doubleWaitTime}\n`;
        code += `        if (ErrorLevel = 0) {\n`; // Pressed again!
        
        if (hasTriple) {
          code += `            ; Released second press\n`;
          code += `            KeyWait, ${key}, T${kHoldSec}\n`;
          code += `            ; Check third press\n`;
          code += `            KeyWait, ${key}, D T${kDoubleSec}\n`;
          code += `            if (ErrorLevel = 0) {\n`;
          code += `                ; --- TRIPLE PRESS ---\n`;
          code += `                ${getActionCodeV1(t, key)}\n`;
          code += `            } else {\n`;
          code += `                ; --- DOUBLE PRESS ---\n`;
          code += `                ${getActionCodeV1(d, key)}\n`;
          code += `            }\n`;
        } else {
          code += `            ; --- DOUBLE PRESS ---\n`;
          code += `            ${getActionCodeV1(d, key)}\n`;
        }
        
        code += `        } else {\n`; // No second press
        code += `            ; --- SINGLE PRESS ---\n`;
        code += `            ${getActionCodeV1(s, key)}\n`;
        code += `        }\n`;
      } else {
        code += `        ; --- SINGLE PRESS ---\n`;
        code += `        ${getActionCodeV1(s, key)}\n`;
      }
      
      code += `    } else {\n`; // Key timed out (Hold)
      code += `        ; --- PRESS AND HOLD ---\n`;
      code += `        ${getActionCodeV1(h, key)}\n`;
      code += `        KeyWait, ${key} ; Wait for physical release\n`;
      code += `    }\n`;
    } else {
      // No hold, just double/triple
      code += `    KeyWait, ${key}, T0.20\n`;
      const doubleWaitTime = hasTriple ? kTripleSec : kDoubleSec;
      code += `    KeyWait, ${key}, D T${doubleWaitTime}\n`;
      code += `    if (ErrorLevel = 0) {\n`;
      
      if (hasTriple) {
        code += `        KeyWait, ${key}, T0.20\n`;
        code += `        KeyWait, ${key}, D T${kDoubleSec}\n`;
        code += `        if (ErrorLevel = 0) {\n`;
        code += `            ; --- TRIPLE PRESS ---\n`;
        code += `            ${getActionCodeV1(t, key)}\n`;
        code += `        } else {\n`;
        code += `            ; --- DOUBLE PRESS ---\n`;
        code += `            ${getActionCodeV1(d, key)}\n`;
        code += `        }\n`;
      } else {
        code += `        ; --- DOUBLE PRESS ---\n`;
        code += `        ${getActionCodeV1(d, key)}\n`;
      }
      
      code += `    } else {\n`;
      code += `        ; --- SINGLE PRESS ---\n`;
      code += `        ${getActionCodeV1(s, key)}\n`;
      code += `    }\n`;
    }

    code += `return\n\n`;
  });

  // 2. Macros Definition (Subroutines)
  if (profile.macros && profile.macros.length > 0) {
    code += `; -------------------------------------------------------------------------\n`;
    code += `; CUSTOM MACROS (SUBROUTINES)\n`;
    code += `; -------------------------------------------------------------------------\n\n`;
    
    profile.macros.forEach(macro => {
      code += `PlayMacro_${macro.id}:\n`;
      code += `    ; Name: ${macro.name}\n`;
      
      if (macro.steps.length === 0) {
        code += `return\n\n`;
      } else {
        macro.steps.forEach((step, idx) => {
          code += compileMacroStepV1(step) + '\n';
          if (macro.useStandardDelays !== false && idx < macro.steps.length - 1) {
            code += `    Sleep, 50\n`;
          }
        });
        code += `return\n\n`;
      }
    });
  }

  return code;
}
